import SwiftUI
import AubadeCore

/// What the app shows, whichever state the morning is in.
public struct AubadeRootView: View {
    @ObservedObject private var store: MorningStore
    @Environment(\.colorScheme) private var colorScheme
    @State private var showingSettings = false

    public init(store: MorningStore) {
        self.store = store
    }

    public var body: some View {
        let theme = Theme.forScheme(colorScheme)
        ZStack {
            theme.palette.newsprint.ignoresSafeArea()
            content
        }
        .environment(\.theme, theme)
        .task { await store.open() }
        .sheet(isPresented: $showingSettings) {
            SetupView(store: store, isPresented: $showingSettings)
                .environment(\.theme, theme)
        }
    }

    @ViewBuilder
    private var content: some View {
        switch store.state {
        case .needsSetup:
            SetupView(store: store, isPresented: .constant(true))

        case .ready(let presentation):
            EditionView(presentation: presentation) { id, action in
                store.record(action, for: id)
            }

        case .preparing(let previous):
            if let previous {
                VStack(spacing: 0) {
                    // Clearly dated, so yesterday's edition is never mistaken for today's.
                    PreviousEditionBanner(presentation: previous)
                    EditionView(presentation: previous)
                }
            } else {
                PreparingView()
            }
        }
    }
}

/// Says plainly which morning you are looking at while today's is assembled.
struct PreviousEditionBanner: View {
    let presentation: EditionPresentation
    @Environment(\.theme) private var theme

    var body: some View {
        HStack(spacing: 8) {
            ProgressView().scaleEffect(0.6)
            Text("Preparing today. This is \(presentation.folioDate).".uppercased())
                .font(theme.type.folio)
                .tracking(1.1)
                .foregroundStyle(theme.palette.inkMuted)
            Spacer(minLength: 0)
        }
        .padding(.horizontal, 19)
        .padding(.vertical, 8)
        .background(theme.palette.rule.opacity(0.4))
    }
}

struct PreparingView: View {
    @Environment(\.theme) private var theme

    var body: some View {
        VStack(spacing: 12) {
            Text("Aubade")
                .font(theme.type.masthead)
                .foregroundStyle(theme.palette.ink)
            Text("Preparing this morning's edition".uppercased())
                .font(theme.type.folio)
                .tracking(1.4)
                .foregroundStyle(theme.palette.inkMuted)
            ProgressView().padding(.top, 4)
        }
    }
}

/// Connecting Quercus.
///
/// A read-only personal access token, generated by the reader and revocable by them at any
/// time. It goes straight to the Keychain and is never written beside the editions, never
/// exported, and never sent anywhere but Quercus.
struct SetupView: View {
    @ObservedObject var store: MorningStore
    @Binding var isPresented: Bool
    @State private var token = ""
    @State private var isSaving = false
    @Environment(\.theme) private var theme

    private let tokenURL = URL(string: "https://q.utoronto.ca/profile/settings")!

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Aubade")
                    .font(theme.type.masthead)
                    .foregroundStyle(theme.palette.ink)
                Rectangle().frame(height: 2.5).foregroundStyle(theme.palette.ink)

                Text("Connect Quercus")
                    .font(theme.type.lead)
                    .foregroundStyle(theme.palette.ink)

                Text("Aubade reads your coursework with a personal access token that you generate and can revoke at any moment. It only ever reads: it cannot submit work, change anything, or see your grades.")
                    .font(theme.type.standfirst)
                    .foregroundStyle(theme.palette.ink)
                    .fixedSize(horizontal: false, vertical: true)

                Link(destination: tokenURL) {
                    Text("Open Quercus settings".uppercased())
                        .font(theme.type.folioEmphasis)
                        .tracking(1.2)
                        .foregroundStyle(theme.palette.spot)
                }

                Text("Account → Settings → New Access Token")
                    .font(theme.type.meta)
                    .foregroundStyle(theme.palette.inkMuted)

                SecureField("Paste the token", text: $token)
                    .textFieldStyle(.plain)
                    .font(theme.type.brief)
                    .foregroundStyle(theme.palette.ink)
                    .padding(9)
                    .overlay { Rectangle().stroke(theme.palette.ink, lineWidth: 1) }

                Button {
                    Task {
                        isSaving = true
                        await store.saveQuercusToken(token.trimmingCharacters(in: .whitespacesAndNewlines))
                        isSaving = false
                        isPresented = false
                    }
                } label: {
                    Text(isSaving ? "Connecting…" : "Connect")
                        .font(theme.type.folioEmphasis)
                        .tracking(1.4)
                        .foregroundStyle(theme.palette.newsprint)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 10)
                        .background(theme.palette.ink)
                }
                .buttonStyle(.plain)
                .disabled(token.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || isSaving)

                Text("The token is stored in the iPhone's Keychain, kept off iCloud and out of backups, and is never included in an export.")
                    .font(theme.type.meta)
                    .foregroundStyle(theme.palette.inkMuted)
                    .fixedSize(horizontal: false, vertical: true)

                if !store.missingFonts.isEmpty {
                    Text("Typography unavailable: \(store.missingFonts.joined(separator: ", "))")
                        .font(theme.type.meta)
                        .foregroundStyle(theme.doubtColor)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .padding(19)
        }
        .background(theme.palette.newsprint.ignoresSafeArea())
    }
}
